feat: maintain cursor position despite formatting
crispgm/nvim-go pull request #41
Opened 2022-03-28 21:27 UTC by telemachus

2022-03-28 21:28 UTC, telemachus commented
Per conversation in #39, I've added a configuration option. I also added the new option to the README and put a note about the option into the docs.

I'm happy to make adjustments if you want, and you should feel free (of course!) to adjust the code to suit your style or how you want the option to work. Thanks for considering this. Let me know if you'd like me to make any changes.

(Sorry for the double pull request. I had to make a quick edit because of a dumb mistake.)

2022-03-29 02:55 UTC, crispgm commented
Thanks for the PR. There is a minor issue. Otherwise, it's perfect.

2022-07-22 02:57 UTC, crispgm requested changes

2022-07-22 02:57 UTC, crispgm commented on README.md
>      -- test flags: -count=1 will disable cache
Please put the new option above this line, because this comments the following options :)

2022-07-22 03:00 UTC, crispgm requested changes

2022-07-22 03:00 UTC, crispgm commented on lua/go/config.lua
> +    maintain_cursor_pos = true,
I think it better to change default to `false`, because it's new feature somehow breaking.

2022-07-22 11:24 UTC, telemachus commented
Thanks for the review. I made the two changes you suggested.

2022-07-24 04:44 UTC, crispgm commented
LGTM but you may have to resolve the conflicts.

2022-07-24 14:02 UTC, telemachus commented
> LGTM but you may have to resolve the conflicts.

@crispgm I'm sorry, but I'm not sure how to do that.

This is the conflict:

```diff
<<<<<<< maintain-cursor-pos
        maintain_cursor_pos = false,
=======
        -- test flags: -count=1 will disable cache
>>>>>>> main
```

I don't see what I can do from my end to fix that,
especially since I have to force push to update this
pull request.

Any suggestions?

2022-07-24 14:08 UTC, telemachus commented
> LGTM but you may have to resolve the conflicts.

Okay, I think I've done that. Let me know if you need
any other changes.

2022-07-25 08:13 UTC, crispgm commented
> 

Looks fine. I will fix some minor style issue and then merge.

2022-07-25 08:37 UTC, merged

2022-07-25 08:37 UTC, crispgm commented
Merged! Thanks very much :) @telemachus