add basic gotests support
crispgm/nvim-go pull request #47
Opened 2022-06-17 16:04 UTC by marcomayer

This adds basic support for https://github.com/cweill/gotests. Hovering over a function doing :GoAddTest adds test for function in _test.go file. I used treesitter to get the function name.

Sorry for the bad lua code, I've very basic knowledge of it, also credits go to https://github.com/ray-x/go.nvim for the idea and part of the code.

2022-06-19 02:37 UTC, crispgm commented
Looks quite good, please check the minor issues I submitted during review.

2022-06-20 17:51 UTC, marcomayer commented
> 

Happy to! Just can't see your comments, maybe you didn't finish the review or there's some permission issue?

2022-06-21 02:21 UTC, crispgm requested changes

2022-06-21 02:21 UTC, crispgm commented on lua/go/gotests.lua
> +        print('no function found')
`output.show_error` here

2022-06-21 02:21 UTC, crispgm commented on lua/go/config.lua
> +    gotests_template = '', -- sets gotests -template parameter (see gotests for details)
a separating comment should be here :)

2022-06-21 02:22 UTC, crispgm commented
> > 
> 
> Happy to! Just can't see your comments, maybe you didn't finish the review or there's some permission issue?

Yes, you are correct. I just submitted the review :)

2022-06-22 13:52 UTC, marcomayer commented
> Yes, you are correct. I just submitted the review :)
Great, thanks! Just updated what was requested, thanks for pointing it out.

2022-06-23 03:03 UTC, crispgm requested changes

2022-06-23 03:03 UTC, crispgm commented on lua/go/config.lua
> +    { name = 'gotests', src = 'github.com/cweill/gotests' },
It looks like that the correct URL is: `github.com/cweill/gotests/gotests`

2022-06-23 03:04 UTC, crispgm commented
@marcomayer And I have one more question: does `GoAddTest` need any parameters?

2022-06-23 04:52 UTC, crispgm commented
@marcomayer just added a commit by myself to fix some stuffs

2022-06-23 12:42 UTC, marcomayer commented
>

2022-06-23 12:44 UTC, marcomayer commented
> @marcomayer And I have one more question: does `GoAddTest` need any parameters?

Nope, you just need to be in or hover at a function when calling it.

2022-06-23 13:11 UTC, crispgm approved these changes

2022-06-23 13:12 UTC, merged

2022-06-23 13:12 UTC, crispgm commented
> > @marcomayer And I have one more question: does `GoAddTest` need any parameters?
> 
> Nope, you just need to be in or hover at a function when calling it.

Okay, I updated the `command` and then merged. Thanks!